name: Update tree
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    regen-tree: 
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Install tree
          run: sudo apt-get update && sudo apt-get install -y tree
        - name: Update directory tree in README
          run: bash script/update_tree.sh
        - name: Commit & push if changed
          run: |
            if ! git diff --exit-code README.md; then
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git commit -am "chore: auto-update directory tree"
                git push
            else
                echo "README.md up to date"
            fi